In [1]:
a = 10
b = 100000000000000000000000000000000000000000

print(a)
print(b)

10
100000000000000000000000000000000000000000


In [2]:
print(0.1 + 0.2) # 0.30000000000000004

0.30000000000000004


In [3]:
c = 3 + 4j

print(c.real) # 실수부 3.0
print(c.imag) # 허수부 4.0

3.0
4.0


In [4]:
# decimal 모듈안에 Decimal함수를 메모리에 로드
# 파이썬 언어가 제공하는 객체중 내장객체가 아닌것들은 import 후 사용
from decimal import Decimal

a = Decimal("0.1") # 인자값을 float으로 전달하면 전달하는 순간 오차가 발생하니 문자열로 입력한다.
b = Decimal("0.2")

print(a + b)

0.3


In [5]:
print(0.1 + 0.2 == 0.3) # False

print(Decimal("0.1") + Decimal("0.2") == Decimal("0.3")) # True

False
True


In [6]:
from fractions import Fraction

f = Fraction(1, 3)

print(f)

# 분수계산의 예
a = Fraction(1, 3)
b = Fraction(1, 6)
c = a + b
print(c)

d = a*b
print(d)

# 분수를 실수로 변환
print(float(c))
print(float(d))

1/3
1/2
1/18
0.5
0.05555555555555555


In [ ]:
a = -1
b = 0
c = 1
d = 2
e = 0.1

print(bool(a)) # True
print(bool(b)) # False (0만 False 뜸)
print(bool(c)) # True
print(bool(d)) # True
print(bool(e)) # True

True
False
True
True
True


In [ ]:
n = 10
print(n.bit_length()) # 10의 이진수 값(1010)의 길이

# bin()함수는 인자로 입력된 10진수의 2진수 문자열을 반환한다.
# 이진수 문자열 앞에 binary를 뜻하는 "0b"접두사를 앞에 붙여서 반환한다. (1010과 10, 10을 구분하기 위함)
print(bin(n)) #0b1010 "0b" + "1010"

# bit_length()메서드는 n이라는 숫자 객체를 만들어야 존재하는 것이고,
# bin() 함수는 n객체와 상관없는 독립된 함수 객체이다.

print(bin(9)) # n과 상관없이 독립적으로 사용가능

4
0b1010
0b1001


In [11]:
print(pow(2, 3)) # 거듭제곱 int로 반환
print(divmod(10, 3)) # 몫과 나머지를 tuple로 반환
print(round(3.14159, 2)) # 반올림된 실수값을 반환
print(abs(-10)) # 절대값을 반환(반환 타입은 인자값과 같은 타입)

8
(3, 1)
3.14
10


In [12]:
pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 12.4/12.4 MB 85.0 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np

a = np.array
print(a)([[1, 2],
              [3, 4]])
print(type(a))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [14]:
([[1, 2], [3, 4]]) + ([[5, 6], [7, 8]])

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [15]:
a = np.array([[1, 2],
              [3, 4]])
print(a)

b = np.array([[5, 6],
              [7, 8]])
print(a + b) 
# [1+5  2+6] 
# [3+7  4+8]

[[1 2]
 [3 4]]
[[ 6  8]
 [10 12]]


In [16]:
# 전치행렬
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [2]:
a = [1, 2, 3]
b = [4, 5]
result = a + b
print(result) # [1, 2, 3, 4, 5]
print(a)
print(b)

[1, 2, 3, 4, 5]
[1, 2, 3]
[4, 5]


In [ ]:
nums = [10, 20]
result = nums * 3
print(result) # [10, 20, 10, 20, 10, 20]

# [30, 60]의 결과를 얻고 싶으면 Numpy 라이브러리로 "행렬객체"를 만들어 사용

[10, 20, 10, 20, 10, 20]


In [4]:
fruits = ["apple", "banana", "orange"]
print("banana" in fruits)

print("grape" in fruits)
print("grape" not in fruits)

True
False
True


In [9]:
nums = [10, 20, 30, 40]

print(nums[0])
print(nums[-1])

# 인덱스 할당 연산
nums[2] = 99 # 리스트는 가변 객체
print(nums)

n2 = (3, 5)
#n2[0] = 999 #object does not support item assignment 튜플은 불변객체이다. 리스트의 읽기전용 객체이다.

10
40
[10, 20, 99, 40]


In [10]:
nums = [10, 20, 30, 40, 50]

print(nums[1:4]) # [20, 30, 40]
print(nums[:3]) # [10, 20, 30]
print(nums[2:]) # [30, 40, 50]
print(nums) #  [10, 20, 30, 40, 50] 슬라이싱 연산 후에도 리스트 자신은 변경되지 않는다. 

# 2칸씩 건너뛰기
nums = [10, 20, 30, 40, 50, 60, 70, 80]
print(nums[::2])

nums = [10, 20, 30, 40, 50, 60, 70, 80]
print(nums[1::2])

# 역순 출력
nums = [10, 20, 30, 40, 50]
print(nums[::-1]) # [50, 40, 30, 20, 10]

# 뒤에서 3개 추출
nums = [10, 20, 30, 40, 50, 60]
print(nums[-3:])

# 뒤에서 4개 중 2칸씩
nums = [10, 20, 30, 40, 50, 60, 70, 80]
print(nums[-4::2])

# 뒤에서 앞으로 2칸씩
nums = [10, 20, 30, 40, 50, 60, 70, 80]
print(nums[::-2])

# [5]위치부터 뒤로(-1) [1]위치 전까지
nums = [10, 20, 30, 40, 50, 60, 70]
print(nums[5:1:-1]) # 5위치부터 1전까지 -1칸식  [60, 50, 40, 30]

# 마지막 5개를 역순으로
nums = [10, 20, 30, 40, 50, 60, 70, 80]
print(nums[-1:-6:-1])

# 슬라이싱 할당(슬라이싱 구간에 대입문)
nums = [10, 20, 30, 40, 50]
nums[1:4] = [7, 8] # 1~3구간 [20, 30, 40]에 [7, 8]을 대입 
print(nums) # [10, 7, 8, 50]

# 슬라이싱 결과를 다른 변수에 대입
a = [10, 20, 30, 40, 50, 60]
b = a[:]
c = a[::-1]
d = a[1::2]
e = a[:2]

print(b)
print(c)
print(d)
print(e)

[20, 30, 40]
[10, 20, 30]
[30, 40, 50]
[10, 20, 30, 40, 50]
[10, 30, 50, 70]
[20, 40, 60, 80]
[50, 40, 30, 20, 10]
[40, 50, 60]
[50, 70]
[80, 60, 40, 20]
[60, 50, 40, 30]
[80, 70, 60, 50, 40]
[10, 7, 8, 50]
[10, 20, 30, 40, 50, 60]
[60, 50, 40, 30, 20, 10]
[20, 40, 60]
[10, 20]


In [11]:
a = [10, 20, 30]
b = a

print(a)
print(b)
print(a == b)
print(a is b)

b[0] = 999
print(a) 
print(b) 

[10, 20, 30]
[10, 20, 30]
True
True
[999, 20, 30]
[999, 20, 30]


In [12]:
nums = [10, 20, 30, 40]

print(len(nums))
nums = [10, 20, 30, 40]

print(max(nums))
print(min(nums))
print(sum(nums))

4
40
10
100


In [ ]:
nums = [50, 10, 40, 20]
n2 = nums.sort(reverse=True) # 내림차순
print(nums)
print(n2) # 정렬만 하고 반환을 하지 않으니까 값이 None으로 나온다. sort()메서드는 리스트 객체를 정렬만 하고 반환하지 않는다.

[50, 40, 20, 10]
None


In [16]:
# insert() : 원하는 위치에 추가
fruits = ["apple", "banana"]
fruits.insert(1, "orange")
print(fruits)


# extend() : 여러 개 추가
nums = [1, 2, 3]
nums.extend([4, 5, 6])
print(nums)


# remove() : 값으로 삭제
fruits = ["apple", "banana", "orange"]
fruits.remove("banana")
print(fruits)


# 수정은 인덱스 할당, 슬라이싱 할당으로 수정
# pop() : 인덱스로 삭제 후 반환
nums = [10, 20, 30]
result = nums.pop() # 마지막 인덱스 삭제 후 반환
print(result)
print(nums)

nums = [10, 20, 30]
result = nums.pop(1) # 인덱스1 삭제 후 반환
print(result)
print(nums)


# clear() : 전체 삭제
nums = [10, 20, 30]
nums.clear()
print(nums)

['apple', 'orange', 'banana']
[1, 2, 3, 4, 5, 6]
['apple', 'orange']
30
[10, 20]
20
[10, 30]
[]


In [ ]:
nums = [10, 20, 30, 40]
del nums[1] # del은 메서드도 함수도 아닌 키워드(예약어)
print(nums)

[10, 30, 40]


In [ ]:
# 튜플은 팩킹과 언팩킹!!!

t = 1, 3, 5 # 팩킹 실행 -> 리스트가 아닌 튜플로 묶어짐
print(t) 
print(type(t)) # <class 'tuple'>

x, y, z = t # 언팩킹 실행
print(x, y, z)

a, b = [3,6] # (3,6) 팩킹 발생
print(a, b)

(1, 3, 5)
<class 'tuple'>
1 3 5
3 6


In [ ]:
# 셋은 집합의 개념 / 중복이 허용되지 않는다 / 순서가 없다 
a = {1, 2, 3, 2}
print(a)
# print(a[0]) # set은 인덱스가 없다
print(list(a)[0]) # set을 list로 변환 후 인덱스로 접근 가능

{1, 2, 3}
1


In [ ]:
a = {"1": "admin", "pw": 1234} # 딕셔너리
print(a, type(a))

b = {3,4,6} # 셋
print(b, type(b))

c = []
print(type(c))

d = {} # 빈 중괄호는 딕셔너리와 셋 중 딕셔너리이다
print(type(d))

e = set() # 빈 set()은 셋이다
print(type(e))

{'1': 'admin', 'pw': 1234} <class 'dict'>
{3, 4, 6} <class 'set'>
<class 'list'>
<class 'dict'>
<class 'set'>


In [ ]:
# 집합 연산은 기호를 사용하거나, 메서드를 사용할 수 있는데 / 기호만으론 가독성이 떨어지니까, 메서드 사용을 권하심
a = {1, 2, 3}
b = {3, 4, 5}

# 교집합
print(a & b) 
print(a.intersection(b))

# 합집합
print(a | b)
print(a.union(b))

# 차집합
print(a - b)
print(a.difference(b))

{3}
{3}
{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5}
{1, 2}
{1, 2}


In [ ]:
# 패킹, 언패킹시 * 연산자 : 나머지 값들은 하나씩 가져가고, * 연산자를 붙인 변수에는 나머지 값들을 리스트(가변객체)로 묶어서 가져간다.
# a, b = [1, 2, 3, 4] 

*a, b = (1, 2, 3, 4)
print(a)
print(b)

c, *d, e = (1, 2, 3, 4)
print(c)
print(d)
print(e)

f = [1, 2, 3]
print(*f) # 1 2 3 # print(h[0], h[1], h[2])와 동일한 결과


[1, 2, 3]
4
1
[2, 3]
4
1 2 3


{}
{}
